feat: FND-1136 moving large tables from fix column width to the propo…
Sanofi-IADC/konviw pull request #315
Opened 2022-02-07 18:17 UTC by EL-HARBYLY-Abderrahman

…rtional percentage per column

2022-02-07 20:05 UTC, PiiXiieeS approved these changes
Nicely done!

2022-02-08 00:15 UTC, kiru42 commented
Looks good to me too, just missing some tests.

2022-02-08 11:41 UTC, PiiXiieeS commented
Yes, indeed missing some tests.

2022-02-09 11:35 UTC, MeStrak requested changes

2022-02-09 11:35 UTC, MeStrak commented on tests/unit/steps/fixColgroupWidth.spec.ts
> +    expect(context.getHtmlBody()).toContain('width: 224.0px;');
The test title is should **not**, but there is no negative test here - if possible you should also test for the thing you expect not to see.

2022-02-15 09:17 UTC, EL-HARBYLY-Abderrahman commented on tests/unit/steps/fixColgroupWidth.spec.ts
> +    expect(context.getHtmlBody()).toContain('width: 224.0px;');
Since there is no change of states before and after the execution of the step for me it is already a negative test
But I can add more details to the test with **not.toContain**

2022-02-15 19:29 UTC, PiiXiieeS approved these changes

2022-02-15 20:03 UTC, MeStrak approved these changes

2022-02-15 20:05 UTC, merged