fix: WEB-178 Removed the default grey th background
Sanofi-IADC/konviw pull request #423
Opened 2022-06-28 13:31 UTC by Zougouda

2022-06-28 22:48 UTC, PiiXiieeS commented
@Zougouda this solution is not complete because default grey brackground used in Confluence tables will be now default to white background.

2022-06-28 23:00 UTC, PiiXiieeS requested changes
We new a more complete check like if no `data-highlight-colour` attribute provided then default to grey, otherwise not apply style so it will take the colour provided in the attribute.

This should display in purple:

```
<th data-highlight-colour="#c0b6f2" class="confluenceTh">
  <p style="text-align: center;">
    <strong>Digital IA &amp; FO Summer Tech Days</strong>
  </p>
</th>
```

while this should default to grey and not to white like in the current proposal:
```
<th class="confluenceTh">
  <p style="text-align: center;">
    <strong>Pros</strong>
  </p>
</th>
```

something like:
```
table.confluenceTable th.confluenceTh:not([data-highlight-colour]),
table.confluenceTable th.confluenceTh:not([data-highlight-colour]) > p {
  background-color: var(--highlight-grey);
}
```

2022-06-28 23:00 UTC, PiiXiieeS requested changes, later dismissed

2022-06-28 23:00 UTC, PiiXiieeS commented on src/assets/scss/_tables.scss
>  /* Background colors */
table.confluenceTable th.confluenceTh:not([data-highlight-colour]),
table.confluenceTable th.confluenceTh:not([data-highlight-colour]) > p {
  background-color: var(--highlight-grey);
}

2022-06-28 23:37 UTC, PiiXiieeS commented
@Zougouda I have committed the changes, take a look and confirm.

2022-06-29 12:50 UTC, Zougouda commented
I approve your changes @PiiXiieeS and took the opportunity to make these css rules a little easier to read/maintain by exploiting the scss syntax a bit better.

2022-06-30 18:38 UTC, merged