Bugfix/web 1805
Sanofi-IADC/konviw pull request #512
Opened 2023-05-19 12:42 UTC by BENBEN5959

fix JQL Query

2023-05-19 13:22 UTC, bonfim-sanofi requested changes
Add tests for this bug.

2023-05-26 14:03 UTC, krystiankedra commented on src/proxy-page/steps/addJira.ts
> +      filter = filter.replace('=', 'in');
Change only filter value if starts from key =

2023-05-31 07:41 UTC, krystiankedra commented on .eslintrc.js
> +        'linebreak-style': 'off',
Please remove it.

2023-05-31 07:45 UTC, krystiankedra commented on tests/e2e/cypress/integration/jira.snapshot.spec.ts
> +      '/wiki/spaces/KONVIW/pages/64075268842/Jira+Snapshot+with+JQL+Query+key',
In which tenant You created those pages ? Konviw or Sanofi ?

2023-05-31 08:01 UTC, BENBEN5959 commented on tests/e2e/cypress/integration/jira.snapshot.spec.ts
> +      '/wiki/spaces/KONVIW/pages/64075268842/Jira+Snapshot+with+JQL+Query+key',
Sanofi confluence

2023-06-01 09:06 UTC, krystiankedra approved these changes

2023-06-01 09:13 UTC, krystiankedra approved these changes

2023-06-01 09:18 UTC, merged